server:
  port: 8081
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mybatis
  application:
    name: service-provider #注册到eureka注册中心的名称


mybatis:
  type-aliases-package: cn.lynu.service.pojo

# 提供eureka服务端的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

