# 配置端口号
server:
  port: 10086
# 配置项目名，这个名字用来注册到eureka中心
spring:
  application:
    name: eureka-server
# eureka服务的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka



